language: php
php:
    - 5.6
    - 7.0
    - 7.1

branches:
  only:
    - /^master$/

before_install:
  - composer install
  - mkdir -p config
  - cp test/resources/config/settings.yml config

script:
  - php vendor/bin/phpcs --standard=PSR2 src test
  - php vendor/bin/phpunit

